### ISSUE TITLE
compress() method not storing

### ISSUE THREAD

**Issue by MehdiBela** [valdergallo/django-compress-field#8]
Hi again,

So as I said in my previous issue, when I use the instance.source.compress() method, file is not stored. 

FILE_COMPRESS_DELETE_OLD_FILE settings is working just fine.

I've spent the morning running through your code and I actually cant see where the issue comes from. This afternoon I'll try on Linux server to see if I have the same issue, as you said it might be OS related. 

Could you please have a look with a Windows computer ? 

_BTW just asking, before finding your package I tried to implement something like your code, but I couldn't remove the old file after compression as it was still used by a process. Is it the reason why you use async package in your code ?_ 

Regards.

**Comment by valdergallo** [comment]
Ok, I'll check the storage in Django 1.11
Because `compress-field` using the `default_storage` to control the files 

https://github.com/valdergallo/django-compress-field/blob/64bb2cdce496e78e9a8a5dfe66b19fe13c6c79c1/compress_field/base.py#L65-L69

**Comment by MehdiBela** [comment]
After spending way too much time trying to debug your package I've surrendered and written a signal handler for this. I post the code below if that can be of any help for anyone in the future.

```
@receiver(post_save)
def create_checksum_and_compress(sender, instance, **kwargs):
        qset = sender.objects.filter(id=instance.id)
        hash_md5 = hashlib.md5()
        try:
            instance.source.file #raises FileNotFoundError
            zipper = zipfile.ZipFile
            old_path = instance.source.path.split('.')[0]
            with zipper(old_path+'.zip', 'w') as archive:
                archive.write(instance.source.path, arcname=os.path.basename(instance.source.path), compress_type=zipfile.ZIP_DEFLATED)
            with open(old_path+'.zip') as f:
                instance.source.delete() #optional, dont implement if one want to keep uncompressed file
                qset.update(source=File(f))
            with open(old_path+'.zip', "rb") as f: # also optional, generates the checksum of the zipped file
                for chunk in iter(lambda: f.read(4096), b""): #for large files
                    hash_md5.update(chunk)
            qset.update(signature=hash_md5.hexdigest())
        except FileNotFoundError:
            pass
```
