### ISSUE TITLE
Import error related to Zip file field

### ISSUE THREAD

**Issue by 098anu098** [valdergallo/django-compress-field#9]
when i  run command python manage.py migrate then this error is generated :- from compress_field import ZipFileField
ImportError: cannot import name 'ZipFileField' from 'compress_field.
Please help resolving it .

**Comment by valdergallo** [comment]
hi hi ... 

Which Django that you are using ?

**Comment by 098anu098** [comment]
Django 3.0.8

**Comment by 098anu098** [comment]
how can i resolve this issue??

**Comment by valdergallo** [comment]
It´s happening because this project is old ... We need refractory the migrations for new Django migrations ... I know that have one way to set custom Fields in migrations ... I need get one free time at night to solve it ...

**Comment by valdergallo** [comment]
Download version v0.10.2
Thanks for help
